name: ml_covid
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - ipykernel
  - pandas
  - openpyxl
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - xgboost